name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Get current date and commit SHA
      id: get_info
      run: |
        echo "RELEASE_TAG=build-${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "RELEASE_NAME=Build from ${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Create or Update GitHub Release and Upload APK
      uses: softprops/action-gh-release@v1
      if: success() # Only create release if build is successful
      with:
        tag_name: ${{ steps.get_info.outputs.RELEASE_TAG }}
        name: ${{ steps.get_info.outputs.RELEASE_NAME }}
        # draft: true # Create as a draft release
        prerelease: false
        files: app/build/outputs/apk/release/*.apk # Path to your APK
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}